version: '3.4'

services:

  iocoind-testnet:
    image: iocoin/iocoind
    container_name: iocoind-testnet
    volumes:
      - ./ioc-data:/ioc/datadir/
      - ./ioc-conf:/ioc/conf/
    ports:
      - "127.0.0.1:43765:43765"
    environment:
      TESTNET: "1"
      RPC_IP: "*"
      STAKING: "0"
      CONF_NAME: "testnet"
