version: '3.4'

services:
  iocoind:
    image: iocoin/iocoind:latest
    container_name: iocoind
    volumes:
      - ./ioc-data:/ioc/datadir/
      - ./ioc-conf:/ioc/conf/
    ports:
      - "127.0.0.1:33765:33765"