version: '3.4'

services:

  iocoind-testnet:
    image: iocoin/iocoind
    container_name: iocoind-testnet-local
    volumes:
      - ./ioc-data:/ioc/datadir/
      - ./ioc-conf:/ioc/conf/
    ports:
      - "43764:43764"
      - "127.0.0.1:43765:43765"
    entrypoint: >
      sh -c "echo Starting two ioc daemons && 
             ./iocoind -datadir=/ioc/datadir/test2 -conf=/ioc/conf/iocoin-test2.conf -logtimestamps -daemon && 
             sleep 10 && echo Ready for RPC calls && 
             ./iocoind -datadir=/ioc/datadir/test1 -conf=/ioc/conf/iocoin-test1.conf -logtimestamps"
